name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: comparison-frontend
      EXPO_BASE_URL: /${{ github.event.repository.name }}
      EXPO_PUBLIC_API_BASE_URL: https://shopsave-f0fub9eee4dhazbr.japaneast-01.azurewebsites.net
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Change to project directory
        run: cd ${{ env.PROJECT_DIR }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Export web app
        run: npm run build:web

      - name: Add SPA fallback
        run: cp dist/index.html dist/404.html

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
